openapi: 3.0.0
info:
  title: Astra DevOps API
  description: "Use this REST API to perform lifecycle actions for DataStax Astra\
    \ databases.</br> </br> To get started, get your application token from your Astra\
    \ database. You can then create, terminate, resize, park, and unpark databases\
    \ using the DevOps API. You cannot park, unpark, or resize serverless databases.\n\
    \n# Authentication\n\n<!-- ReDoc-Inject: <security-definitions> -->"
  contact:
    email: ad-astra@datastax.com
  version: 2.0.0
servers:
- url: https://api.astra.datastax.com
security:
- BearerAuth:
  - org-db-create
  - org-db-terminate
  - org-db-view
  - org-db-expand
  - org-db-suspend
  - db-keyspace-create
  - db-cql
tags:
- name: Operations
  description: The DevOps APIs are for interacting with Astra databases and all aspects
    of their lifecycle
paths:
  /v2/databases:
    get:
      tags:
      - Operations
      summary: Returns a list of databases
      description: Get a list of databases visible to the user
      operationId: listDatabases
      security:
      - BearerAuth:
        - org-db-view
    post:
      tags:
      - Operations
      summary: Create a new database
      description: Takes a user provided databaseInfo and returns the uuid for a new
        database
      operationId: createDatabase
      security:
      - BearerAuth:
        - org-db-create
  /v2/databases/{databaseID}:
    get:
      tags:
      - Operations
      summary: Finds database by ID
      description: Returns specified database
      operationId: getDatabase
      security:
      - BearerAuth:
        - org-db-view
  /v2/databases/{databaseID}/keyspaces/{keyspaceName}:
    post:
      tags:
      - Operations
      summary: Adds keyspace into database
      description: Adds the specified keyspace to the database
      operationId: addKeyspace
      security:
      - BearerAuth:
        - db-keyspace-create
  /v2/databases/{databaseID}/secureBundleURL:
    post:
      tags:
      - Operations
      summary: Obtain zip for connecting to the database
      description: "Returns a temporary URL to download a zip file with certificates\
        \ for connecting to the database. The URL expires after five minutes.<p>There\
        \ are two types of the secure bundle URL: <ul><li><b>Internal</b> - Use with\
        \ VPC peering connections to use private networking and avoid public internet\
        \ for communication.</li> <li><b>External</b> - Use with any connection where\
        \ the public internet is sufficient for communication between the application\
        \ and the Astra database with MTLS.</li></ul> Both types support MTLS for\
        \ communication via the driver.</p>"
      operationId: generateSecureBundleURL
      security:
      - BearerAuth:
        - db-cql
  /v2/databases/{databaseID}/terminate:
    post:
      tags:
      - Operations
      summary: Terminates a database
      description: Terminates a database
      operationId: terminateDatabase
      security:
      - BearerAuth:
        - org-db-terminate
  /v2/databases/{databaseID}/park:
    post:
      tags:
      - Operations
      summary: Parks a database
      description: Parks a database
      operationId: parkDatabase
      security:
      - BearerAuth:
        - org-db-suspend
  /v2/databases/{databaseID}/unpark:
    post:
      tags:
      - Operations
      summary: Unparks a database
      description: Unparks a database
      operationId: unparkDatabase
      security:
      - BearerAuth:
        - org-db-suspend
  /v2/databases/{databaseID}/resize:
    post:
      tags:
      - Operations
      summary: Resizes a database
      description: Resizes a database. Total number of capacity units desired should
        be specified. Reducing a size of a database is not supported at this time.
      operationId: resizeDatabase
      security:
      - BearerAuth:
        - org-db-expand
  /v2/databases/{databaseID}/resetPassword:
    post:
      tags:
      - Operations
      summary: Resets Password
      description: Sets a database password to the one specified in POST body
      operationId: resetPassword
      security:
      - BearerAuth:
        - org-db-create
  /v2/availableRegions:
    get:
      tags:
      - Operations
      summary: Returns supported regions and availability for a given user and organization
      description: "Returns all supported tier, cloud, region, count, and capacitity\
        \ combinations"
      operationId: listAvailableRegions
      security:
      - BearerAuth:
        - org-db-create
components:
  securitySchemes:
    BearerAuth:
      type: http
      description: A token must be passed in header to access the API
      scheme: bearer
