/*
 * Astra DevOps API
 *
 * Use this REST API to perform lifecycle actions for DataStax Astra databases.</br> </br> To get started, get your application token from your Astra database. You can then create, terminate, resize, park, and unpark databases using the DevOps API. You cannot park, unpark, or resize serverless databases.  # Authentication  <!-- ReDoc-Inject: <security-definitions> -->
 *
 * API version: 2.0.0
 * Contact: ad-astra@datastax.com
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

// Database contains the key information about a database
type Database struct {
	Id string `json:"id"`
	OrgId string `json:"orgId"`
	OwnerId string `json:"ownerId"`
	Info *DatabaseInfo `json:"info"`
	// CreationTime in ISO RFC3339 format
	CreationTime string `json:"creationTime,omitempty"`
	// TerminationTime in ISO RFC3339 format
	TerminationTime string `json:"terminationTime,omitempty"`
	Status *StatusEnum `json:"status"`
	Storage *Storage `json:"storage,omitempty"`
	AvailableActions []string `json:"availableActions,omitempty"`
	// Message to the customer about the cluster
	Message string `json:"message,omitempty"`
	StudioUrl string `json:"studioUrl,omitempty"`
	GrafanaUrl string `json:"grafanaUrl,omitempty"`
	CqlshUrl string `json:"cqlshUrl,omitempty"`
	GraphqlUrl string `json:"graphqlUrl,omitempty"`
	DataEndpointUrl string `json:"dataEndpointUrl,omitempty"`
}
