/*
 * Astra DevOps API
 *
 * Use this REST API to perform lifecycle actions for DataStax Astra databases.</br> </br> To get started, get your application token from your Astra database. You can then create, terminate, resize, park, and unpark databases using the DevOps API. You cannot park, unpark, or resize serverless databases.  # Authentication  <!-- ReDoc-Inject: <security-definitions> -->
 *
 * API version: 2.0.0
 * Contact: ad-astra@datastax.com
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

// AvailableRegionCombination defines a Tier, cloud provider, region combination
type AvailableRegionCombination struct {
	Tier string `json:"tier"`
	CloudProvider string `json:"cloudProvider"`
	Region string `json:"region"`
	Cost *Costs `json:"cost"`
	DatabaseCountUsed int32 `json:"databaseCountUsed"`
	DatabaseCountLimit int32 `json:"databaseCountLimit"`
	CapacityUnitsUsed int32 `json:"capacityUnitsUsed"`
	CapacityUnitsLimit int32 `json:"capacityUnitsLimit"`
	DefaultStoragePerCapacityUnitGb int32 `json:"defaultStoragePerCapacityUnitGb"`
}
