/*
 * Astra DevOps API
 *
 * Use this REST API to perform lifecycle actions for DataStax Astra databases.</br> </br> To get started, get your application token from your Astra database. You can then create, terminate, resize, park, and unpark databases using the DevOps API. You cannot park, unpark, or resize serverless databases.  # Authentication  <!-- ReDoc-Inject: <security-definitions> -->
 *
 * API version: 2.0.0
 * Contact: ad-astra@datastax.com
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

// A mapping of astra node to a customer node currently in use
type MigrationProxyMapping struct {
	// ip on which the node currently in use is accessible
	OriginIP string `json:"originIP"`
	// port on which the node currently in use is accessible
	OriginPort int32 `json:"originPort"`
	// the number of the rack, usually 0, 1, or 2
	Rack int32 `json:"rack"`
	// The number of the node in a given rack, starting with 0
	RackNodeOrdinal int32 `json:"rackNodeOrdinal"`
}
