/*
 * Astra DevOps API
 *
 * Use this REST API to perform lifecycle actions for DataStax Astra databases.</br> </br> To get started, get your application token from your Astra database. You can then create, terminate, resize, park, and unpark databases using the DevOps API. You cannot park, unpark, or resize serverless databases.  # Authentication  <!-- ReDoc-Inject: <security-definitions> -->
 *
 * API version: 2.0.0
 * Contact: ad-astra@datastax.com
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

// DatabaseInfo is the user-provided information describing a database
type DatabaseInfo struct {
	// Name of the database--user friendly identifier
	Name string `json:"name,omitempty"`
	// Keyspace name in database
	Keyspace string `json:"keyspace,omitempty"`
	// This is the cloud provider where the database lives.
	CloudProvider string `json:"cloudProvider,omitempty"`
	// With the exception of classic databases, all databases are serverless. Classic databases can no longer be created with the DevOps API.
	Tier string `json:"tier,omitempty"`
	// Capacity units were used for classic databases, but are not used for serverless databases. Enter 1 CU for serverless databases. Classic databases can no longer be created with the DevOps API.
	CapacityUnits int32 `json:"capacityUnits,omitempty"`
	// Region refers to the cloud region.
	Region string `json:"region,omitempty"`
	// User is the user to access the database
	User string `json:"user,omitempty"`
	// Password for the user to access the database
	Password string `json:"password,omitempty"`
	// Additional keyspaces names in database
	AdditionalKeyspaces []string `json:"additionalKeyspaces,omitempty"`
}
