/*
 * Astra DevOps API
 *
 * Use this REST API to perform lifecycle actions for DataStax Astra databases.</br> </br> To get started, get your application token from your Astra database. You can then create, terminate, resize, park, and unpark databases using the DevOps API. You cannot park, unpark, or resize serverless databases.  # Authentication  <!-- ReDoc-Inject: <security-definitions> -->
 *
 * API version: 2.0.0
 * Contact: ad-astra@datastax.com
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

type ServiceAccountTokenInput struct {
	// The organization name in a more human readable format
	ClientName string `json:"clientName"`
	// The unique identifier for the client for authentication
	ClientId string `json:"clientId"`
	// The UUID client secret for the service account from the create service account response in the user interface
	ClientSecret string `json:"clientSecret"`
}
