/*
 * Astra DevOps API
 *
 * Use this REST API to perform lifecycle actions for DataStax Astra databases.</br> </br> To get started, get your application token from your Astra database. You can then create, terminate, resize, park, and unpark databases using the DevOps API. You cannot park, unpark, or resize serverless databases.  # Authentication  <!-- ReDoc-Inject: <security-definitions> -->
 *
 * API version: 2.0.0
 * Contact: ad-astra@datastax.com
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

// CredsURL from which the creds zip may be downloaded
type CredsUrl struct {
	// DownloadURL is only valid for about 5 minutes
	DownloadURL string `json:"downloadURL"`
	// Internal DownloadURL is only valid for about 5 minutes
	DownloadURLInternal string `json:"downloadURLInternal,omitempty"`
	// Migration Proxy DownloadURL is only valid for about 5 minutes
	DownloadURLMigrationProxy string `json:"downloadURLMigrationProxy,omitempty"`
	// Internal Migration Proxy DownloadURL is only valid for about 5 minutes
	DownloadURLMigrationProxyInternal string `json:"downloadURLMigrationProxyInternal,omitempty"`
}
