/*
 * Astra DevOps API
 *
 * Use this REST API to perform lifecycle actions for DataStax Astra databases.</br> </br> To get started, get your application token from your Astra database. You can then create, terminate, resize, park, and unpark databases using the DevOps API. You cannot park, unpark, or resize serverless databases.  # Authentication  <!-- ReDoc-Inject: <security-definitions> -->
 *
 * API version: 2.0.0
 * Contact: ad-astra@datastax.com
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

type Costs struct {
	CostPerMinCents float64 `json:"costPerMinCents,omitempty"`
	CostPerHourCents float64 `json:"costPerHourCents,omitempty"`
	CostPerDayCents float64 `json:"costPerDayCents,omitempty"`
	CostPerMonthCents float64 `json:"costPerMonthCents,omitempty"`
	CostPerMinParkedCents float64 `json:"costPerMinParkedCents,omitempty"`
	CostPerHourParkedCents float64 `json:"costPerHourParkedCents,omitempty"`
	CostPerDayParkedCents float64 `json:"costPerDayParkedCents,omitempty"`
	CostPerMonthParkedCents float64 `json:"costPerMonthParkedCents,omitempty"`
}
