/*
 * Astra DevOps API
 *
 * Use this REST API to perform lifecycle actions for DataStax Astra databases.</br> </br> To get started, get your application token from your Astra database. You can then create, terminate, resize, park, and unpark databases using the DevOps API. You cannot park, unpark, or resize serverless databases.  # Authentication  <!-- ReDoc-Inject: <security-definitions> -->
 *
 * API version: 2.0.0
 * Contact: ad-astra@datastax.com
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

// UserPassword specifies a username and new password. The specified password will be updated for the specified database user
type UserPassword struct {
	Username string `json:"username,omitempty"`
	// New password (min 6 characters)
	Password string `json:"password,omitempty"`
}
