/*
 * Astra DevOps API
 *
 * Use this REST API to perform lifecycle actions for DataStax Astra databases.</br> </br> To get started, get your application token from your Astra database. You can then create, terminate, resize, park, and unpark databases using the DevOps API. You cannot park, unpark, or resize serverless databases.  # Authentication  <!-- ReDoc-Inject: <security-definitions> -->
 *
 * API version: 2.0.0
 * Contact: ad-astra@datastax.com
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

// CapacityUnits is used to horizontally scale a database.
type CapacityUnits struct {
	// CapacityUnits an be increased by a max of three additional capacity units per operation. Reducing capacity units is not supported at this time
	CapacityUnits int32 `json:"capacityUnits,omitempty"`
}
