/*
 * Astra DevOps API
 *
 * Use this REST API to perform lifecycle actions for DataStax Astra databases.</br> </br> To get started, get your application token from your Astra database. You can then create, terminate, resize, park, and unpark databases using the DevOps API. You cannot park, unpark, or resize serverless databases.  # Authentication  <!-- ReDoc-Inject: <security-definitions> -->
 *
 * API version: 2.0.0
 * Contact: ad-astra@datastax.com
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

type StatusEnum string

// List of StatusEnum
const (
	ACTIVE_StatusEnum StatusEnum = "ACTIVE"
	PENDING_StatusEnum StatusEnum = "PENDING"
	PREPARING_StatusEnum StatusEnum = "PREPARING"
	PREPARED_StatusEnum StatusEnum = "PREPARED"
	INITIALIZING_StatusEnum StatusEnum = "INITIALIZING"
	PARKED_StatusEnum StatusEnum = "PARKED"
	PARKING_StatusEnum StatusEnum = "PARKING"
	UNPARKING_StatusEnum StatusEnum = "UNPARKING"
	TERMINATED_StatusEnum StatusEnum = "TERMINATED"
	TERMINATING_StatusEnum StatusEnum = "TERMINATING"
	RESIZING_StatusEnum StatusEnum = "RESIZING"
	ERROR__StatusEnum StatusEnum = "ERROR"
	MAINTENANCE_StatusEnum StatusEnum = "MAINTENANCE"
	UNKNOWN_StatusEnum StatusEnum = "UNKNOWN"
)
