#!/bin/bash
# Copyright 2021 Ryan Svihla
#
#   Licensed under the Apache License, Version 2.0 (the « License »);
#   you may not use this file except in compliance with the License.
#   You may obtain a copy of the License at
#
#       http://www.apache.org/licenses/LICENSE-2.0
#
#   Unless required by applicable law or agreed to in writing, software
#   distributed under the License is distributed on an « AS IS » BASIS,
#   WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
#   See the License for the specific language governing permissions and
#   limitations under the License.

# script/bootstrap: Resolve all dependencies that the application requires to
#                   run.




if ! command -v go &> /dev/null
then
    echo "os $(uname -s) arch $(uname -m)"
    if [ "$(uname -s)" = "Darwin" ]; then
        echo "install via homebrew"
        brew update
        brew install go
    fi

    if [ "$(uname -s)" = "Linux" ] && [ "$(uname -m)" = "armv7l" ]; then
        echo "arm found installing go"
        curl -L -O https://golang.org/dl/go1.16.linux-armv6l.tar.gz
        sudo tar -C /usr/local -xzf go1.16.linux-armv6l.tar.gz
        echo "add ‘export PATH=\$PATH:/usr/local/go/bin’ to your .bashrc"
        rm go1.16.linux-armv6l.tar.gz
    fi

    if [ "$(uname -s)" = "Linux" ] && [ "$(uname -m)" = "amd64" ]; then
        echo "amd64 found installing go"
        curl -L -O https://golang.org/dl/go1.16.linux-amd64.tar.gz
        sudo tar -C /usr/local -xzf go1.16.linux-amd64.tar.gz
        echo "add 'export PATH=\$PATH:/usr/local/go/bin' to your .bashrc"
        rm go1.16.linux-arm64.tar.gz
    fi

else
    echo "go installed skipping"
fi

if ! command -v golangci-lint &> /dev/null
then
    curl -sSfL https://raw.githubusercontent.com/golangci/golangci-lint/master/install.sh | sh -s -- -b $(go env GOPATH)/bin v1.36.0
else
    echo "golangci-lint installed skipping"
fi
