#!/bin/bash
# Copyright 2022 DataStax
#
#   Licensed under the Apache License, Version 2.0 (the « License »);
#   you may not use this file except in compliance with the License.
#   You may obtain a copy of the License at
#
#       http://www.apache.org/licenses/LICENSE-2.0
#
#   Unless required by applicable law or agreed to in writing, software
#   distributed under the License is distributed on an « AS IS » BASIS,
#   WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
#   See the License for the specific language governing permissions and
#   limitations under the License.

# script/package: build and tgz all supported platforms and architectures

DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" >/dev/null 2>&1 && pwd )"
$DIR/clean
VERSION=$(git describe --abbrev=0 --tags)
ORIG=$(git branch --show-current)
echo "packaging $VERSION$"
git checkout $VERSION
GOOS=darwin GOARCH=amd64 go build -o bin/astra .
tar czvf ./bin/astra-$VERSION-darwin-amd64.tgz ./bin/astra
GOOS=darwin GOARCH=arm64 go build -o bin/astra .
tar czvf ./bin/astra-$VERSION-darwin-arm64.tgz ./bin/astra
GOOS=linux GOARCH=amd64 go build -o bin/astra .
tar czvf ./bin/astra-$VERSION-linux-amd64.tgz ./bin/astra
GOOS=linux GOARCH=arm64 go build -o bin/astra .
tar czvf ./bin/astra-$VERSION-linux-arm64.tgz ./bin/astra
git checkout $ORIG
