#!/bin/bash
# Copyright 2021 Ryan Svihla
#
#   Licensed under the Apache License, Version 2.0 (the « License »);
#   you may not use this file except in compliance with the License.
#   You may obtain a copy of the License at
#
#       http://www.apache.org/licenses/LICENSE-2.0
#
#   Unless required by applicable law or agreed to in writing, software
#   distributed under the License is distributed on an « AS IS » BASIS,
#   WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
#   See the License for the specific language governing permissions and
#   limitations under the License.

# script/test: Run test suite for application. 


t="/tmp/go-cover.$$.tmp"
go test -race -covermode=atomic  -coverprofile=$t ./... && go tool cover -func=$t 
last=$?
unlink $t || true
if [ "$last" = "0" ]; then
    echo "successfully ran"
else
    (exit 1)
fi

